language: php

php:
        - "5.4"

matrix:
        allow_failures:
                - php: 5.5

script: "VERBOSE=true ./tests/run-tests.sh -s tests/"

before_script:
        - composer self-update
        - composer install --dev
        - sudo chmod 777 -R ./